name: Bug
description: File a bug/issue
labels: ["bug"]
body:
- type: markdown
  attributes:
    value: |
      ## INTRODUCTION
    
      Thank you for taking the time to submit a bug report. We'll try to promptly review your bug report, but please note that support on most of our open-source software is provided on a best-effort basis. Please review repository documentation for more details on support status.
      
      ### POSTING INSTRUCTIONS
      
      Before posting, please search the list of existing issues (including closed issues) to see whether a similar bug report already exists. If so, please comment on the existing bug report if necessary, rather than posting a new one.
      
      If applicable, please assign the appropriate labels to this bug report from the `Labels` section on the right-hand side of this form. 
      
      All fields on this form accept Markdown-formatted text. Please make sure to use proper Markdown formatting, like using proper literal text/code blocks for sample commands, stack traces, etcetera. Please use the Preview tab on each field to review how your input will be formatted.
      
      ### CONFIDENTIALITY WARNING
      
      This is a public system; anyone on the internet can read the information you provide in this form. As such, please take extra care *not* to include any confidential data, which may include:

      - Personal Identifiable Information (PII) like names, email addresses, phone numbers, ...
      - Company/customer/tenant names
      - Private URLs that expose the host names of your Fortify or other products
      - Credentials like usernames, passwords or tokens

      Such information is often inadvertently exposed in screen shots, log files, or example command invocations. Although we do prefer full logs and screenshots, please make sure to redact any such confidential or PII data before posting.
- type: textarea
  attributes:
    label: Current Behavior
    description: A concise description of what you're experiencing.    
  validations:
    required: false
- type: textarea
  attributes:
    label: Expected Behavior
    description: A concise description of what you expected to happen.
  validations:
    required: false
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. In this environment...
      1. With this config...
      1. Run '...'
      1. See error...
  validations:
    required: false
- type: textarea
  attributes:
    label: Environment
    description: |
      examples:
        - **OS**: Ubuntu 20.04
        - **SSC**: 24.2.0
        - **fcli**: 2.4.0
    placeholder: |
        Describe the environment in which you're experiencing the issue, like operating system, product versions, ...
    render: markdown
  validations:
    required: false
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in. Please ensure that screenshots or log files don't contain any confidential data.
  validations:
    required: false
