name: Bug
description: File a bug/issue
labels: ["bug"]
body:
- type: markdown
  attributes:
    value: |
      Thank you for taking the time to submit a bug report. Support on most of our open-source software is provided on a best-effort basis, but we'll do our best to review your bug report and provide a fix as necessary. Please review repository documentation for more details on support status.
      
      # FORMATTING
      
      All fields on this form accept Markdown-formatted text. Please make sure to use proper Markdown formatting, like using proper literal text/code blocks for sample commands, stack traces, etcetera. After posting, please review your issue for any incorrect formatting and edit accordingly if necessary.
      
      # CONFIDENTIALITY WARNING
      
      This is a public system; anyone on the internet can read the information you provide in this form. As such, please take extra care *not* to include any confidential data, which may include:

      - Personal Identifiable Information (PII) like names, email addresses, phone numbers, ...
      - Company/customer/tenant names
      - Private URLs that expose the host names of your Fortify or other products
      - Credentials like usernames, passwords or tokens

      Such information is commonly exposed in screen shots, log files, or example command invocations. Although we do prefer full logs and screenshots, please make sure to redact any such confidential or PII data before posting.
- type: textarea
  attributes:
    label: Current Behavior
    description: A concise description of what you're experiencing.    
  validations:
    required: false
- type: textarea
  attributes:
    label: Expected Behavior
    description: A concise description of what you expected to happen.
  validations:
    required: false
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. In this environment...
      1. With this config...
      1. Run '...'
      1. See error...
  validations:
    required: false
- type: textarea
  attributes:
    label: Environment
    description: |
      examples:
        - **OS**: Ubuntu 20.04
        - **SSC**: 24.2.0
        - **fcli**: 2.4.0
    placeholder: |
        Describe the environment in which you're experiencing the issue, like Operating System, product versions, ...
    render: markdown
  validations:
    required: false
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in. Please ensure that screenshots or log files don't contain any confidential data.
  validations:
    required: false
