name: Question
description: Submit a question
labels: ["question"]
body:
- type: markdown
  attributes:
    value: |
      ## INTRODUCTION
    
      Thank you for taking the time to raise a question. We'll try to promptly review your question, but please note that support on most of our open-source software is provided on a best-effort basis. Please review repository documentation for more details on support status.
      
      ### POSTING INSTRUCTIONS
      
      Before posting, please search the list of existing issues (including closed issues) to see whether a similar question already exists. If so, please comment on the existing question if necessary, rather than posting a new one.
      
      If applicable, please assign the appropriate labels to this question from the `Labels` section on the right-hand side of this form. 
      
      All fields on this form accept Markdown-formatted text. Please make sure to use proper Markdown formatting, like using proper literal text/code blocks for sample commands, stack traces, etcetera. Please use the Preview tab on each field to review how your input will be formatted.
      
      ### CONFIDENTIALITY WARNING
      
      This is a public system; anyone on the internet can read the information you provide in this form. As such, please take extra care *not* to include any confidential data, which may include:

      - Personal Identifiable Information (PII) like names, email addresses, phone numbers, ...
      - Company/customer/tenant names
      - Private URLs that expose the host names of your Fortify or other products
      - Credentials like usernames, passwords or tokens

      Such information is often inadvertently exposed in screen shots, log files, or example command invocations. Although we do prefer full logs and screenshots, please make sure to redact any such confidential or PII data before posting.
- type: textarea
  attributes:
    label: Question
    description: The question that you'd like us to answer. Include as many details/context as needed, but please refrain from including any confidential data.    
  validations:
    required: true
